# my global config
global:
  scrape_interval: 15s 
  evaluation_interval: 15s 

scrape_configs:
  - job_name: 'jenkins'
    static_configs:
      - targets: ['34.98.76.232:80']
  - job_name: 'webapp'
    static_configs:
      - targets: ['34.87.119.57:8000']